const actionTypes = {
  FETCHING_RESOLVED: 'TODOS.FETCHING_RESOLVED',
  SET_CURRENT_TODOS: 'TODOS.SET_CURRENT_TODOS',
  ADD_CATEGORY: 'TODOS.ADD_CATEGORY',
  ADDING_NESTED_CATEGORY: 'TODOS.ADDING_NESTED_CATEGORY',
  SET_FILTER: 'TODOS.SET_FILTER',
  SET_CURRENT_TASK: 'TODOS.SET_CURRENT_TASK',
  PICKED_CATEGORY: 'TODOS.PICKED_CATEGORY',
  UNDO: 'TODOS.UNDO',
};

export default actionTypes;
