const actionTypes = {
  FETCHING_RESOLVED: 'TODOS.FETCHING_RESOLVED',
  SET_CURRENT_TODOS: 'TODOS.SET_CURRENT_TODOS',
  ADD_CATEGORY: 'TODOS.ADD_CATEGORY',
  ADDING_NESTED_CATEGORY: 'TODO.ADDING_NESTED_CATEGORY',
  SET_FILTER: 'TODO.SET_FILTER',
  SET_CURRENT_TASK: 'TODO.SET_CURRENT_TASK'
};

export default actionTypes;
